### ISSUE TITLE
Failed to create resource. 'DomainValidationOptions'

### ISSUE THREAD

**Issue by wangwalton** [tobilg/serverless-aws-static-websites#1]
I bought a domain on namecheap, when I run sls deploy --domain domain.com with the domain I bought I get the above error. Is there further configuration required to use external domains?

**Comment by tobilg** [comment]
Did you configure the Namecheap DNS while deploying as described in https://github.com/tobilg/serverless-aws-static-websites#manual-update-of-dns-records-on-first-deploy

**Comment by tobilg** [comment]
Any feedback @wangwalton? Thanks!

**Comment by tobilg** [comment]
Closing, please reopen if the problem persists.
