### ISSUE TITLE
Please provide the code for the obfuscated lambda python code

### ISSUE THREAD

**Issue by mihaiblaga89** [tobilg/serverless-aws-static-websites#2]
It's hard to unobfuscate an indentation based language. I want to see what does it do exactly and maybe change it to suit my needs if necessary. Thanks

**Comment by tobilg** [comment]
It‘s not „obfuscated“, it‘s minimized. You can find a link to the original source repo at https://github.com/tobilg/serverless-aws-static-websites/blob/master/resources/custom-acm-certificate-lambda.yml#L5

I‘ll not provide a separate Version in this repo, sorry.
