### ISSUE TITLE
 Failed to create resource. Certificate not issued in time

### ISSUE THREAD

**Issue by GaryNg-R** [tobilg/serverless-aws-static-websites#3]
when I first deploy the application,  it just come up this error, 

SSLCertificate | CREATE_FAILED | Failed to create resource. Certificate not issued in time

i did do the following step in my routh53 to change the NS record 

The nameservers you have to configure your domain DNS to can be found under the `NS` record and will look similar to this:
```bash
ns-1807.awsdns-33.co.uk.
ns-977.awsdns-58.net.
ns-1351.awsdns-40.org.
ns-32.awsdns-04.com.
```

**Comment by tobilg** [comment]
Are you using a Route53 domain, or an external one, e.g. Namecheap etc.?

**Comment by GaryNg-R** [comment]
yes, i am using Route53 domain , i try both to change the NS record and not change still fail

**Comment by tobilg** [comment]
Ok, that means you already have a HostedZone for your Route53 domain I assume. If so, you'd just need to reference the HostedZone via it's ID here:

* https://github.com/tobilg/serverless-aws-static-websites/blob/master/resources/dns-records.yml#L11
* https://github.com/tobilg/serverless-aws-static-websites/blob/master/resources/dns-records.yml#L25

You can then also comment out https://github.com/tobilg/serverless-aws-static-websites/blob/master/serverless.yml#L42 so that the new HostedZone isn't created.

**Comment by GaryNg-R** [comment]
i had one before.. .but i thought that block the process and i thought the script will generate a new hosted zone for me so i delete it. let me manually create it back and try again later. Thanks

**Comment by GaryNg-R** [comment]
i manually add back a hosted zone, and change the HostedZone ID and comment out the HostedZone.yml,   then it just throw another error 

  Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [HostedZone] in the Resources block of the template

then i uncomment that, it just run into the SSLCertificate - Failed to create resource. Certificate not issued in time. error again

**Comment by tobilg** [comment]
Ah, sorry, you have to comment out the references to the HostedZone resource as well, e.g. 

* https://github.com/tobilg/serverless-aws-static-websites/blob/master/resources/dns-records.yml#L8
* https://github.com/tobilg/serverless-aws-static-websites/blob/master/resources/dns-records.yml#L22

**Comment by GaryNg-R** [comment]
so i try but look like it has AccessDenied error, so what if i delete the HostedZone, and just want the script created everything for me, what i need to do fix the ssl create issue 


Thanks for answering my question

**Comment by GaryNg-R** [comment]
just want to see if you have any update, I delete everything and try to deploy everything as new but still not working, it fail on SSLCertificate part

**Comment by GaryNg-R** [comment]
> just want to see if you have any update, I delete everything and try to deploy everything as new but still not working, it fail on SSLCertificate part

I find what wrong with that ssl issue...i was update the HostZone ns in the wrong way..i should update my domain ns to match the new hostZone ns .

**Comment by tobilg** [comment]
Great you got it working!
